### ISSUE TITLE
Need a choice of themes for the widget and transparency

### ISSUE THREAD

**Issue by userkilled** [gooGofZ/BitcoinTimechainWidgets#12]
Using a smartphone with 10 android I have a problem. I have dark letters and a transparent background, and I need light letters and numbers for the dark wallpaper.
Thanks.

**Comment by KadeLehman** [comment]
Yeah for my fee viewer widget, I want to have the dark blue background show up for dark mode, not the light background. Or even better, transparent with text color option.

**Comment by gooGofZ** [comment]
Thank you for the feedback.
Already fixed the dark theme on Android 10+. #13  (app version 1.3.2)
